site_name: 浅蓝色西柚の日記
site_description: 浅蓝色西柚的个人网站

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: white
    accent: light blue
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 主页: index.md
  - 课程: course/index.md
  - 友链: friends/index.md
  - 关于: about/index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
