site_name: 浅蓝色西柚の日記
site_description: 浅蓝色西柚的个人网站
site_url: https://tayor1.github.io/

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    scheme: default
    primary: white
    accent: light blue
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 主页: index.md
  - "日记&随想": diary/index.md
  - 番剧记录站: anime/index.md
  - 课程: course/index.md
  - 友链: friends/index.md
  - 关于: about/index.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
